spring:
  application:
    name: hello-spring-cloud-service-sso
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  zipkin:
    base-url: http://localhost:9411
  redis: 
    database: 0
    host: 106.15.186.202
    port: 6379
    password: AZ2.3sdfawsx23
    max-idle: 8
  thymeleaf:
    cache: false #开发时关闭缓存,实时页面
    mode: LEGACYHTML5 #非严格得html
    encoding: UTF-8
    servlet:
      content-type: text/html

feign:
  hystrix:
    enabled: true


server:
  port: 9990

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/